# Generated by Django 3.2 on 2022-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_articles',
            field=models.BooleanField(default=False),
        ),
    ]
