# Generated by Django 3.2 on 2022-04-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField(max_length=900)),
            ],
        ),
    ]
