# Generated by Django 3.2 on 2022-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='Product',
            new_name='product',
        ),
    ]
