# Generated by Django 3.2 on 2022-04-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='date_published',
        ),
    ]
