# Generated by Django 3.2 on 2022-04-11 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productreview_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
